"""empty message

Revision ID: 3d7dbd0cf918
Revises: f7292c480452
Create Date: 2025-01-13 00:11:09.533496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7dbd0cf918'
down_revision = 'f7292c480452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_constraint('cars_seller_id_fkey', type_='foreignkey')
        batch_op.drop_column('seller_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('cars_seller_id_fkey', 'sellers', ['seller_id'], ['id'])

    # ### end Alembic commands ###
