"""empty message

Revision ID: 9f743933744f
Revises: 
Create Date: 2025-01-30 02:06:46.622305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f743933744f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password', sa.String(length=180), nullable=False),
    sa.Column('salt', sa.String(length=140), nullable=False),
    sa.Column('country', sa.Enum('USA', 'Canada', 'Ecuador', 'Argentina', 'Chile', 'Brazil', 'Germany', 'Spain', 'Japan', 'China', name='sellers_country'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=90), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=180), nullable=False),
    sa.Column('salt', sa.String(length=130), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('country', sa.Enum('USA', 'Canada', 'Ecuador', 'Argentina', 'Chile', 'Brazil', 'Germany', 'Spain', 'Japan', 'China', 'Other', name='country'), nullable=False),
    sa.Column('avatar', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_make_id', sa.String(length=80), nullable=False),
    sa.Column('model_name', sa.String(length=180), nullable=False),
    sa.Column('model_trim', sa.String(length=180), nullable=False),
    sa.Column('model_year', sa.String(length=180), nullable=False),
    sa.Column('model_body', sa.String(length=180), nullable=False),
    sa.Column('model_engine_position', sa.String(length=180), nullable=True),
    sa.Column('model_engine_cc', sa.String(length=180), nullable=True),
    sa.Column('model_engine_cyl', sa.String(length=180), nullable=True),
    sa.Column('model_engine_type', sa.String(length=180), nullable=True),
    sa.Column('model_engine_valves_per_cyl', sa.String(length=180), nullable=True),
    sa.Column('model_engine_power_ps', sa.String(length=180), nullable=True),
    sa.Column('model_engine_power_rpm', sa.String(length=180), nullable=True),
    sa.Column('model_engine_torque_nm', sa.String(length=180), nullable=True),
    sa.Column('model_engine_torque_rpm', sa.String(length=180), nullable=True),
    sa.Column('model_engine_bore_mm', sa.String(length=180), nullable=True),
    sa.Column('model_engine_compression', sa.String(length=180), nullable=True),
    sa.Column('model_engine_fuel', sa.String(length=180), nullable=True),
    sa.Column('model_top_speed_kph', sa.String(length=180), nullable=True),
    sa.Column('model_0_to_100_kph', sa.String(length=180), nullable=True),
    sa.Column('model_drive', sa.String(length=180), nullable=True),
    sa.Column('model_transmission_type', sa.Enum('Automatic', 'Manual', name='transmission'), nullable=True),
    sa.Column('model_seats', sa.String(length=180), nullable=True),
    sa.Column('model_doors', sa.String(length=180), nullable=True),
    sa.Column('model_weight_kg', sa.String(length=180), nullable=True),
    sa.Column('model_length_mm', sa.String(length=180), nullable=True),
    sa.Column('model_width_mm', sa.String(length=180), nullable=True),
    sa.Column('model_height_mm', sa.String(length=180), nullable=True),
    sa.Column('model_wheelbase_mm', sa.String(length=180), nullable=True),
    sa.Column('model_lkm_hwy', sa.String(length=180), nullable=True),
    sa.Column('model_lkm_mixed', sa.String(length=180), nullable=True),
    sa.Column('model_lkm_city', sa.String(length=180), nullable=True),
    sa.Column('model_fuel_cap_l', sa.String(length=180), nullable=True),
    sa.Column('model_sold_in_us', sa.String(length=180), nullable=True),
    sa.Column('model_co2', sa.String(length=180), nullable=True),
    sa.Column('model_make_display', sa.String(length=180), nullable=True),
    sa.Column('make_display', sa.String(length=180), nullable=True),
    sa.Column('make_country', sa.String(length=180), nullable=False),
    sa.Column('model_amount', sa.String(length=120), nullable=False),
    sa.Column('model_price', sa.String(length=180), nullable=False),
    sa.Column('model_picture', sa.String(length=180), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    op.drop_table('user')
    op.drop_table('sellers')
    # ### end Alembic commands ###
