"""empty message

Revision ID: fa85127f5cdb
Revises: 224ea7b946e0
Create Date: 2025-01-20 22:28:56.212214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa85127f5cdb'
down_revision = '224ea7b946e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.alter_column('model_transmission_type',
               existing_type=postgresql.ENUM('Automatic', 'Manual', name='transmission'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.alter_column('model_transmission_type',
               existing_type=postgresql.ENUM('Automatic', 'Manual', name='transmission'),
               nullable=False)

    # ### end Alembic commands ###
